version: "1"

services:
  service-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  service-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - service-postgres
    environment:
      - DB_URL=${DB_URL}
    restart: always

volumes:
  db_volume: 
  